### ISSUE TITLE
Магические числа

### ISSUE THREAD

**Issue by bonvech** [AlexanderMaximov520/Miracle-Field#1]
В программе встречаются магические числа: 
1039 < ord(bukva) < 1104
64 < ord(i) < 91

Для чего они? Они будут одинаковые в разных кодировках?

**Comment by AlexanderMaximov520** [comment]
С помощью условия "if 1039 < ord(bukva) < 1104" можно понять, русская ли буква введена пользователем. Дело в том, что русские буквы в таблице Юникода находятся между этими номерами, а команда "ord" определяет номер буквы. Вроде как условие "if 64 < ord(i) < 91" определяет, введена большая буква или нет. Но самое главное то, что можно обойтись без его использования, а если я его не использую, зачем мне это объяснять, верно (этого условия больше нет в коде) ? К слову, есть также условие 1039 < ord(bukva) < 1072, если оно верное, то буква большая, если нет - маленькая.

**Comment by bonvech** [comment]
В других кодировках коды этих букв разные. 
Если использовать функцию ord('я'), то где бы мы не запускали программу, какая бы там не была кодировка, это всегда будет код буквы 'я'. И в тексте программы также сразу понятно, что это такое написано, мы же не всегда помним код букв.
