### ISSUE TITLE
Недостижимое условие

### ISSUE THREAD

**Issue by bonvech** [AlexanderMaximov520/Miracle-Field#2]
Одно из условий цикла никогда не может быть верным.
while kolvo_popitok != 0

**Comment by AlexanderMaximov520** [comment]
Да, вы правы. На ранних стадиях программирования игры цикл выполнялся, но внезапно перестал. Цикл стал бесконечным. Я нашел такое решение проблемы - если в конце условия про угадывание буквы слово совпадало с загаданным, происходил выход из цикла с помощью "break", также в конце условия о том, что пользователь не угадал букву, при количестве попыток равном 0 происходил выход из цикла с помощью "break". А про переименование условия цикла я и забыл. Условие цикла исправлено и теперь понятно, что он является бесконечным (пока не сработает "break" или команда "сдаться").
